// <auto-generated />
namespace ViFlix.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddColumnsInAspNetUsersTableToMakeItCompatibleWithNetcore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddColumnsInAspNetUsersTableToMakeItCompatibleWithNetcore));

        string IMigrationMetadata.Id
        {
            get { return "201809231442573_addColumnsInAspNetUsersTableToMakeItCompatibleWithNetcore"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
